#!/usr/bin/env python3
"""
talk.py -- the framing-doc loop, end to end: English in -> bits -> BIT-NATIVE CORE -> bits -> English out.

This is the "Bit-Native Intelligence Core with Dumb Modality Adapters" demo (BIT_NATIVE_INTELLIGENCE_
FRAMING.md). The adapter is *dumb* (UTF-8 bytes <-> bits, no semantics). The core is a bit-native
next-bit predictor (byte-aware context model with backoff, the same family that compresses enwik8):
trained on real English, it GENERATES a response by autoregressively sampling the next bit from its own
prediction, one bit at a time, and the adapter decodes the bits back to text.

Honest scope: this is a *byte-level statistical* language model (like a high-order n-gram / small
char-LM), NOT an instruction-tuned LLM. It does not "reason" or "answer" -- it CONTINUES the prompt in
the style of its training corpus. The point is to make the architecture's I/O loop real and visible:
prediction = the substrate, language = a dumb adapter on top.

Usage:
  python talk.py "your prompt here"          # one response
  python talk.py                             # interactive: type prompts, Ctrl-C to quit
  python talk.py --corpus data/corpus_big.txt --train 1500000 --gen 400 --temp 0.7 "prompt"
"""
import sys, random, math

ORDERS = [0, 1, 2, 3, 4, 5, 6]   # byte-aware context orders to back off through (high -> low)


# --- the DUMB adapter: text <-> bytes <-> bits (MSB first), no semantics ---
def text_to_bits(s):
    bits = []
    for b in s.encode("utf-8", "replace"):
        for j in range(7, -1, -1):
            bits.append((b >> j) & 1)
    return bits


def bits_to_text(bits):
    out = bytearray()
    for k in range(0, len(bits) - 7, 8):
        byte = 0
        for j in range(8):
            byte = (byte << 1) | bits[k + j]
        out.append(byte)
    return out.decode("utf-8", "replace")


# --- the BIT-NATIVE CORE: byte-aware context model, trained then sampled ---
def addr(bits, i, B):
    """order-B byte-aware context known strictly before bit i: phase + partial byte + B previous bytes."""
    phase = i & 7
    bstart = i - phase
    return (phase, bytes(bits[bstart:i]), bytes(bits[max(0, bstart - B * 8):bstart]))


def train(bits, tables, alpha=0.25):
    """Stream the corpus bits, accumulating next-bit counts per context per order (online, causal)."""
    for i in range(len(bits)):
        y = bits[i]
        for B in ORDERS:
            t = tables[B]
            k = addr(bits, i, B)
            c = t.get(k)
            if c is None:
                c = [0, 0]; t[k] = c
            c[y] += 1


def predict(bits, i, tables, alpha=0.25, thresh=1):
    """P(next bit = 1): highest order whose context has been seen enough, KT/Laplace-smoothed; else 0.5."""
    for B in reversed(ORDERS):                      # high order first, back off
        c = tables[B].get(addr(bits, i, B))
        if c is not None and (c[0] + c[1]) >= thresh:
            return (c[1] + alpha) / (c[0] + c[1] + 2 * alpha)
    return 0.5


def generate(prompt, tables, n_gen_bytes=300, temp=0.8, seed=0):
    rng = random.Random(seed)
    bits = text_to_bits(prompt)                     # prime the core with the prompt (its context)
    start = len(bits)
    for _ in range(n_gen_bytes * 8):
        p1 = predict(bits, len(bits), tables)
        if temp != 1.0:                             # temperature on the bit (sharpen/flatten)
            a = p1 ** (1.0 / temp)
            b = (1.0 - p1) ** (1.0 / temp)
            p1 = a / (a + b) if (a + b) > 0 else 0.5
        bit = 1 if rng.random() < p1 else 0
        bits.append(bit)
    return bits_to_text(bits[start:])


def load_corpus(path, cap):
    raw = open(path, "rb").read()
    if cap:
        raw = raw[:cap]
    bits = []
    for b in raw:
        for j in range(7, -1, -1):
            bits.append((b >> j) & 1)
    return raw, bits


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")  # generated bytes may be any value
    except Exception:
        pass
    args = sys.argv[1:]
    corpus = "data/corpus_big.txt"
    train_cap = 800000
    gen_bytes = 300
    temp = 0.8
    prompt = None
    i = 0
    while i < len(args):
        if args[i] == "--corpus":
            corpus = args[i + 1]; i += 2
        elif args[i] == "--train":
            train_cap = int(args[i + 1]); i += 2
        elif args[i] == "--gen":
            gen_bytes = int(args[i + 1]); i += 2
        elif args[i] == "--temp":
            temp = float(args[i + 1]); i += 2
        else:
            prompt = args[i]; i += 1

    print("=" * 78)
    print("BIT-NATIVE CORE + dumb text adapter  (English -> bits -> core -> bits -> English)")
    print("=" * 78)
    try:
        raw, bits = load_corpus(corpus, train_cap)
    except FileNotFoundError:
        print(f"corpus {corpus} not found; try --corpus data/corpus.txt"); return
    print(f"training the bit-native core on {len(raw)} bytes of English ({len(bits)} bits)...", flush=True)
    tables = {B: {} for B in ORDERS}
    train(bits, tables)
    print(f"trained. contexts learned (order-6) = {len(tables[6])}. temp={temp}\n")

    def respond(p):
        pb = text_to_bits(p)
        print(f"[you]      {p!r}")
        print(f"[adapter]  English -> {len(p.encode('utf-8','replace'))} bytes -> {len(pb)} bits")
        print(f"[core]     sampling {gen_bytes} next-bytes ({gen_bytes*8} bits), one bit at a time ...")
        out = generate(p, tables, n_gen_bytes=gen_bytes, temp=temp, seed=0)
        print(f"[adapter]  bits -> bytes -> English")
        print(f"[core says] {p}|{out}")
        print("-" * 78)

    if prompt is not None:
        respond(prompt)
    else:
        # a few demo prompts, then an interactive loop
        for p in ["The meaning of life is ", "Once upon a time ", "She opened the door and "]:
            respond(p)
        print("(interactive: type a prompt and press Enter; Ctrl-C to quit)")
        try:
            while True:
                p = input("\n[you] ")
                if p.strip():
                    respond(p if p.endswith(" ") else p + " ")
        except (KeyboardInterrupt, EOFError):
            print("\nbye.")


if __name__ == "__main__":
    main()
